$(document).on('ready',function() {
	$('select[name=area').tooltip({
		placement:"right",
		trigger:"hover"
	});
	$('select[name=topografia').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('select[name=institucion').tooltip({
		placement:"right",
		trigger:"hover"
	});
	$('select[name=servicio').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('select[name=medicot').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('input:text[name=medicotr]').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('span[name=fechas]').tooltip({
		placement:"right",
		trigger:"hover"
	});
	$('select[name=tipo').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('select[name=tecnologo').tooltip({
		placement:"top",
		trigger:"focus"
	});
	$('select[name=patologo').tooltip({
		placement:"top",
		trigger:"focus"
	});
	$('textarea[name=diagnosticoc]').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('textarea[name=observacion]').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('span[name=pgb]').tooltip({
		placement:"right",
		trigger:"hover"
	});
	$('span[name=dm1]').tooltip({
		placement:"right",
		trigger:"hover"
	});
	$('span[name=fb2]').tooltip({
		placement:"right",
		trigger:"hover"
	});
	$('input:text[name=gesta]').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('input:text[name=para]').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('input:text[name=mac]').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('input:text[name=fur]').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('input:text[name=pap]').tooltip({
		placement:"right",
		trigger:"focus"
	});
	$('select[name=mremitida').tooltip({
		placement:"top",
		trigger:"focus"
	});
	$('button[name=admed').tooltip({
		placement:"top",
		trigger:"hover"
	});
})